CREATE TABLE SRC_STORE (
    STORE_ID VARCHAR2(20),
    PRODUCT_ID VARCHAR2(20),
    STORE_NAME VARCHAR2(100),
    CITY VARCHAR2(100),
    STORE_CATEGORY VARCHAR2(50),
    OPERATIONAL_STATUS VARCHAR2(20)
);

CREATE TABLE SRC_PRODUCT (
    PRODUCT_ID VARCHAR2(20),
    PRODUCT_NAME VARCHAR2(100),
    PRODUCT_CATEGORY VARCHAR2(50),
    UNIT_PRICE NUMBER(10,2),
    PRODUCT_STATUS VARCHAR2(20)
);

CREATE TABLE SRC_SALES (
    SALES_ID VARCHAR2(20),
    STORE_ID VARCHAR2(20),
    PRODUCT_ID VARCHAR2(20),
    QUANTITY_SOLD NUMBER,
    UNIT_PRICE NUMBER(10,2),
    TOTAL_AMOUNT NUMBER(10,2),
    SALES_DATE DATE
);

CREATE TABLE SRC_INVENTORY (
    INVENTORY_ID VARCHAR2(20),
    PRODUCT_ID VARCHAR2(20),
    AVAILABLE_STOCK NUMBER,
    REORDER_LEVEL NUMBER,
    INVENTORY_STATUS VARCHAR2(30),
    ALERT_FLAG VARCHAR2(5)
);

CREATE TABLE MASTER_RETAIL_DATA (
    MASTER_ID VARCHAR2(20),
    STORE_ID VARCHAR2(20),
    PRODUCT_ID VARCHAR2(20),
    SALES_ID VARCHAR2(20),
    INVENTORY_ID VARCHAR2(20),
    STORE_NAME VARCHAR2(100),
    CITY VARCHAR2(100),
    PRODUCT_NAME VARCHAR2(100),
    PRODUCT_CATEGORY VARCHAR2(50),
    QUANTITY_SOLD NUMBER,
    UNIT_PRICE NUMBER(10,2),
    TOTAL_AMOUNT NUMBER(10,2),
    SALES_DATE DATE,
    AVAILABLE_STOCK NUMBER,
    REORDER_LEVEL NUMBER,
    INVENTORY_STATUS VARCHAR2(30),
    ALERT_FLAG VARCHAR2(5),
    LOAD_DATE TIMESTAMP
);