CREATE TABLE TGT_PRODUCT_CLEAN (
    PRODUCT_ID VARCHAR2(20),
    PRODUCT_NAME VARCHAR2(100),
    PRODUCT_CATEGORY VARCHAR2(50),
    UNIT_PRICE NUMBER(10,2),
    PRODUCT_STATUS VARCHAR2(20)
);

CREATE TABLE TGT_PRODUCT_ACTIVE (
    PRODUCT_ID VARCHAR2(20),
    PRODUCT_NAME VARCHAR2(100),
    PRODUCT_CATEGORY VARCHAR2(50),
    UNIT_PRICE NUMBER(10,2)
);

CREATE TABLE TGT_PRODUCT_PRICE_ANALYSIS (
    PRODUCT_ID VARCHAR2(20),
    PRODUCT_NAME VARCHAR2(100),
    UNIT_PRICE NUMBER(10,2),
    PRICE_CATEGORY VARCHAR2(30)
);

CREATE TABLE TGT_PRODUCT_REJECT (
    PRODUCT_ID VARCHAR2(20),
    PRODUCT_NAME VARCHAR2(100),
    REJECT_REASON VARCHAR2(255)
);

CREATE TABLE TGT_STORE_ACTIVE (
    STORE_ID VARCHAR2(20),
    PRODUCT_ID VARCHAR2(20),
    STORE_NAME VARCHAR2(100),
    CITY VARCHAR2(100),
    STORE_CATEGORY VARCHAR2(50)
);

CREATE TABLE TGT_STORE_CITY (
    CITY VARCHAR2(100),
    TOTAL_STORES NUMBER
);

CREATE TABLE TGT_STORE_CATEGORY (
    STORE_CATEGORY VARCHAR2(50),
    TOTAL_STORES NUMBER
);

CREATE TABLE TGT_STORE_REJECT (
    STORE_ID VARCHAR2(20),
    STORE_NAME VARCHAR2(100),
    REJECT_REASON VARCHAR2(255)
);

CREATE TABLE TGT_SALES_DAILY (
    SALES_ID VARCHAR2(20),
    STORE_ID VARCHAR2(20),
    PRODUCT_ID VARCHAR2(20),
    TOTAL_AMOUNT NUMBER(10,2),
    SALES_DATE DATE
);

CREATE TABLE TGT_SALES_HIGH_REVENUE (
    SALES_ID VARCHAR2(20),
    PRODUCT_ID VARCHAR2(20),
    TOTAL_AMOUNT NUMBER(10,2)
);

CREATE TABLE TGT_SALES_PRODUCT_SUMMARY (
    PRODUCT_ID VARCHAR2(20),
    TOTAL_QUANTITY NUMBER,
    TOTAL_REVENUE NUMBER(12,2)
);

CREATE TABLE TGT_SALES_REJECT (
    SALES_ID VARCHAR2(20),
    REJECT_REASON VARCHAR2(255)
);

CREATE TABLE TGT_STOCK_AVAILABLE (
    INVENTORY_ID VARCHAR2(20),
    PRODUCT_ID VARCHAR2(20),
    AVAILABLE_STOCK NUMBER
);

CREATE TABLE TGT_LOW_STOCK_ALERT (
    INVENTORY_ID VARCHAR2(20),
    PRODUCT_ID VARCHAR2(20),
    AVAILABLE_STOCK NUMBER,
    REORDER_LEVEL NUMBER,
    ALERT_FLAG VARCHAR2(5)
);

CREATE TABLE TGT_REORDER_ANALYSIS (
    PRODUCT_ID VARCHAR2(20),
    AVAILABLE_STOCK NUMBER,
    REORDER_LEVEL NUMBER,
    STOCK_STATUS VARCHAR2(30)
);

CREATE TABLE TGT_INVENTORY_REJECT (
    INVENTORY_ID VARCHAR2(20),
    REJECT_REASON VARCHAR2(255)
);

CREATE TABLE TGT_REGION_PERFORMANCE (
    CITY VARCHAR2(100),
    TOTAL_REVENUE NUMBER(12,2)
);

CREATE TABLE TGT_PRODUCT_PERFORMANCE (
    PRODUCT_ID VARCHAR2(20),
    PRODUCT_NAME VARCHAR2(100),
    TOTAL_REVENUE NUMBER(12,2)
);

CREATE TABLE TGT_EXECUTIVE_DASHBOARD (
    CITY VARCHAR2(100),
    PRODUCT_CATEGORY VARCHAR2(50),
    TOTAL_SALES NUMBER(12,2),
    AVAILABLE_STOCK NUMBER
);